name: API Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install -g newman
    - name: Run tests
      run: |
        newman run Writing test scripts-postman_collection.json -e Writing test scripts-postman_collection.json
